### ISSUE TITLE
Can i get transactionhash before contract execute callback?

### ISSUE THREAD

**Issue by gyn7561** [trufflesuite/truffle-contract#110] opened 2018-04-08 03:02 UTC

**Comment by cgewecke** [comment] 2018-05-16 20:43
@gyn7561 This feature is available as part of an upgrade to `web3 1.0` which is now available in an experimental nightly build here: [darq-truffle@next](https://www.npmjs.com/package/darq-truffle). 
```shell
$ npm install -g darq-truffle@next
$ darq-truffle test # Example command
```

Usage docs [here](https://github.com/trufflesuite/truffle-contract/blob/web3-one-readme/README.md)

Closing as a duplicate of [truffle 652](https://github.com/trufflesuite/truffle/issues/652)

**Closed by cgewecke** 2018-05-16 20:43 UTC
